### ISSUE TITLE
How to train to get clf.pkl and a bug related to clf.pkl

### ISSUE THREAD

**Issue by anny0316** [MarcusOlivecrona/REINVENT#12]
Hello, when I run train_agent.py, the line of code in "scoring_functions.py"：
score = self.clf.predict_proba(fp)[:, 1]
 that's throwing the error is: AttributeError: 'SVC' object has no attribute '_probA',

 that calls this line in _base.py: 
def _predict_proba(self, X):
    X = self._validate_for_predict(X)
    if self.probA_.size == 0 or self.probB_.size == 0:

which calls this line, also in _base.py:
@property
def probA_(self):
    return self._probA

It is caused by calling the model clf.pkl, which needs to be retrained for solveing the error. Can you help me, thanks a lot.

**Comment by hautshiwy** [comment]
Traceback (most recent call last):
  File "main.py", line 59, in <module>
    train_agent(**arg_dict)
  File "E:\REINVENT-master\train_agent.py", line 85, in train_agent
    score = scoring_function(smiles)
  File "E:\REINVENT-master\scoring_functions.py", line 173, in __call__
    scores = [self.scoring_function(smile) for smile in smiles]
  File "E:\REINVENT-master\scoring_functions.py", line 173, in <listcomp>
    scores = [self.scoring_function(smile) for smile in smiles]
  File "E:\REINVENT-master\scoring_functions.py", line 80, in __call__
    score = self.clf.predict_proba(fp)
  File "C:\Users\hauts\Anaconda3\envs\my-rdkit-env\lib\site-packages\sklearn\svm\_base.py", line 662, in _predict_proba
    if self.probA_.size == 0 or self.probB_.size == 0:
  File "C:\Users\hauts\Anaconda3\envs\my-rdkit-env\lib\site-packages\sklearn\svm\_base.py", line 759, in probA_
    return self._probA
AttributeError: 'SVC' object has no attribute '_probA'

I have also same question. what should i do?

**Comment by MarcusOlivecrona** [comment]
This is due to an incompatibility between sklearn version. There really should have been a requirement.txt with exact versions used, but a quick search indicates that this problem arose with sklearn versions > 0.21, so you could try to use a version below that.
